title: Erlang Ecosystem Foundation CNA
description: This project handles the CVE Numbering Authority (CNA) for the Erlang Ecosystem Foundation (EEF).

plugins:
- jekyll-remote-theme
- jekyll-datapage-generator
- jekyll-include-cache
- jekyll-sitemap
- jekyll-redirect-from

page_gen-dirs: true
page_gen:
- data: cves
  template: cve
  dir: cves
  index_files: false
  name_expr: 'record["cveMetadata"]["cveId"]'
  title_expr: 'record["containers"]["cna"]["title"] || record["cveMetadata"]["cveId"]'
  extension: html
- data: cves
  template: cve_json
  dir: cves
  index_files: false
  name_expr: 'record["cveMetadata"]["cveId"]'
  extension: json
  page_data_prefix: cve
- data: osv
  template: osv_json
  dir: osv
  index_files: false
  name_expr: 'record["id"]'
  extension: json
  page_data_prefix: osv

repository: erlef-cna/website
remote_theme: erlef/eef-jekyll-theme@v0.2.0

# Disable safe mode to allow custom plugins
safe: false

sass:
  sass_dir: _sass
