title: Erlang Ecosystem Foundation CNA
description: This project handles the CVE Numbering Authority (CNA) for the Erlang Ecosystem Foundation (EEF).

plugins:
- jekyll-remote-theme
- jekyll-datapage-generator
- jekyll-include-cache

page_gen-dirs: true
page_gen:
- data: cves
  template: cve
  dir: cves
  index_files: false
  name_expr: 'record["cveMetadata"]["cveId"]'
  title_expr: 'record["containers"]["cna"]["title"] || record["cveMetadata"]["cveId"]'

repository: erlef-cna/website
remote_theme: erlef/eef-jekyll-theme@v0.2.0

sass:
  sass_dir: _sass
